// This file is auto-generated by npm-functions/generate-blog-manifest-ts.js
// Do not edit manually - regenerate using: npm run blog:update-manifest

export const BLOG_MANIFEST = {
  "files": [
    {
      "fileName": "hello-blog.md",
      "title": "Hello Blog",
      "cover": "hello-blog.png",
      "subtitle": "Testing blog post, please ignore. Explains how populating this blog works.",
      "date": "2025-08-26T05:00:00.000Z",
      "tags": [
        "markdown",
        "angular",
        "obsidian",
        "node"
      ]
    }
  ]
} as const;
